#!/usr/bin/env python3
"""Train a dual-head recurrent model for ballast-preview wind forecasting.

The model follows the dataset design in
``data/processed/wind_ml_10min/ballast_decision_dwd_helgoland``:

- input: past 12 ten-minute wind states and multi-resolution features;
- regression output: future 6-step wind-vector sequence in scaled u/v form;
- classification output: future wind-change event probabilities.

The script intentionally keeps preprocessing outside training. It uses the
existing train-only scalers and chronological splits generated by the data
preparation step, then writes metrics and checkpoints into an output folder.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch import nn


SPLITS = ["train", "validation", "test"]


@dataclass
class TrainConfig:
    dataset_dir: str
    output_dir: str
    epochs: int
    batch_size: int
    hidden_size: int
    num_layers: int
    dropout: float
    learning_rate: float
    weight_decay: float
    event_loss_weight: float
    direction_loss_weight: float
    patience: int
    lr_patience: int
    lr_factor: float
    seed: int
    threads: int
    shuffle_blocks: bool
    threshold_mode: str
    residual_regression: bool
    model_type: str
    device: str


class WindRNN(nn.Module):
    def __init__(
        self,
        input_size: int,
        hidden_size: int,
        future_steps: int,
        event_count: int,
        num_layers: int,
        dropout: float,
        model_type: str,
    ) -> None:
        super().__init__()
        recurrent_dropout = dropout if num_layers > 1 else 0.0
        self.future_steps = future_steps
        model_type = model_type.lower()
        if model_type == "lstm":
            recurrent_cls = nn.LSTM
        elif model_type == "gru":
            recurrent_cls = nn.GRU
        else:
            raise ValueError(f"Unsupported recurrent model type: {model_type}")
        self.model_type = model_type
        self.recurrent = recurrent_cls(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            dropout=recurrent_dropout,
            batch_first=True,
        )
        self.shared = nn.Sequential(
            nn.LayerNorm(hidden_size),
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Dropout(dropout),
        )
        self.regression_head = nn.Linear(hidden_size, future_steps * 2)
        self.event_head = nn.Linear(hidden_size, event_count)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        if self.model_type == "lstm":
            _, (hidden, _) = self.recurrent(x)
        else:
            _, hidden = self.recurrent(x)
        features = self.shared(hidden[-1])
        uv = self.regression_head(features).view(x.shape[0], self.future_steps, 2)
        event_logits = self.event_head(features)
        return uv, event_logits


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dataset-dir",
        type=Path,
        default=Path("data/processed/wind_ml_10min/ballast_decision_dwd_helgoland"),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("outputs/wind_prediction/lstm_ballast_decision"),
    )
    parser.add_argument("--epochs", type=int, default=6)
    parser.add_argument("--batch-size", type=int, default=4096)
    parser.add_argument("--hidden-size", type=int, default=64)
    parser.add_argument("--num-layers", type=int, default=1)
    parser.add_argument("--dropout", type=float, default=0.10)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--weight-decay", type=float, default=1e-5)
    parser.add_argument("--event-loss-weight", type=float, default=0.10)
    parser.add_argument(
        "--direction-loss-weight",
        type=float,
        default=0.0,
        help="Weight for a speed-weighted wind-vector direction loss computed in raw u/v space.",
    )
    parser.add_argument("--patience", type=int, default=3)
    parser.add_argument("--lr-patience", type=int, default=2)
    parser.add_argument("--lr-factor", type=float, default=0.5)
    parser.add_argument("--seed", type=int, default=20260425)
    parser.add_argument("--threads", type=int, default=max(1, min(8, os.cpu_count() or 1)))
    parser.add_argument("--no-shuffle-blocks", action="store_true")
    parser.add_argument("--threshold-mode", choices=["fixed_0.5", "best_f1"], default="best_f1")
    parser.add_argument(
        "--residual-regression",
        action="store_true",
        help="Train the regression head to predict future scaled u/v changes relative to the latest input u/v.",
    )
    parser.add_argument("--model-type", choices=["lstm", "gru"], default="lstm")
    parser.add_argument("--device", choices=["auto", "cpu", "cuda", "mps"], default="auto")
    return parser.parse_args()


def choose_device(requested: str) -> torch.device:
    if requested == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        if torch.backends.mps.is_available():
            return torch.device("mps")
        return torch.device("cpu")
    if requested == "cuda" and not torch.cuda.is_available():
        raise SystemExit("CUDA was requested but is not available.")
    if requested == "mps" and not torch.backends.mps.is_available():
        raise SystemExit("MPS was requested but is not available.")
    return torch.device(requested)


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_arrays(dataset_dir: Path, split: str) -> dict[str, np.ndarray]:
    return {
        "X": np.load(dataset_dir / f"X_{split}.npy", mmap_mode="r"),
        "y_uv": np.load(dataset_dir / f"y_uv_{split}.npy", mmap_mode="r"),
        "y_uv_raw": np.load(dataset_dir / f"y_uv_raw_{split}.npy", mmap_mode="r"),
        "y_speed_dir_raw": np.load(dataset_dir / f"y_speed_dir_raw_{split}.npy", mmap_mode="r"),
        "y_event": np.load(dataset_dir / f"y_event_{split}.npy", mmap_mode="r"),
    }


def load_dataset(dataset_dir: Path) -> tuple[dict[str, dict[str, np.ndarray]], dict, dict]:
    metadata = json.loads((dataset_dir / "metadata.json").read_text(encoding="utf-8"))
    scaler = json.loads((dataset_dir / "scaler_train.json").read_text(encoding="utf-8"))
    arrays = {split: load_arrays(dataset_dir, split) for split in SPLITS}
    return arrays, metadata, scaler


def iter_slices(n: int, batch_size: int, rng: np.random.Generator, shuffle_blocks: bool) -> list[tuple[int, int]]:
    starts = list(range(0, n, batch_size))
    if shuffle_blocks:
        rng.shuffle(starts)
    return [(start, min(start + batch_size, n)) for start in starts]


def event_pos_weight(y_event_train: np.ndarray) -> np.ndarray:
    rates = np.asarray(y_event_train[:], dtype=np.float32).mean(axis=0)
    rates = np.clip(rates, 1e-4, 1 - 1e-4)
    weights = (1.0 - rates) / rates
    return np.clip(weights, 1.0, 50.0).astype("float32")


def numpy_batch(array: np.ndarray, start: int, end: int, dtype: np.dtype = np.float32) -> torch.Tensor:
    return torch.from_numpy(np.array(array[start:end], dtype=dtype, copy=True))


def regression_target(
    y_uv: torch.Tensor,
    x: torch.Tensor,
    residual_regression: bool,
    uv_feature_indices: tuple[int, int],
) -> torch.Tensor:
    if not residual_regression:
        return y_uv
    current_uv = x[:, -1, list(uv_feature_indices)].unsqueeze(1)
    return y_uv - current_uv


def full_scaled_prediction(
    pred_regression: torch.Tensor,
    x: torch.Tensor,
    residual_regression: bool,
    uv_feature_indices: tuple[int, int],
) -> torch.Tensor:
    if not residual_regression:
        return pred_regression
    current_uv = x[:, -1, list(uv_feature_indices)].unsqueeze(1)
    return pred_regression + current_uv


def wind_direction_loss(
    pred_regression: torch.Tensor,
    y_uv_scaled: torch.Tensor,
    x: torch.Tensor,
    residual_regression: bool,
    uv_feature_indices: tuple[int, int],
    target_uv_mean: torch.Tensor,
    target_uv_std: torch.Tensor,
) -> torch.Tensor:
    pred_scaled = full_scaled_prediction(pred_regression, x, residual_regression, uv_feature_indices)
    pred_raw = pred_scaled * target_uv_std + target_uv_mean
    true_raw = y_uv_scaled * target_uv_std + target_uv_mean

    pred_norm = torch.linalg.vector_norm(pred_raw, dim=-1).clamp_min(1e-3)
    true_norm = torch.linalg.vector_norm(true_raw, dim=-1).clamp_min(1e-3)
    cosine = (pred_raw * true_raw).sum(dim=-1) / (pred_norm * true_norm)
    angular = 1.0 - cosine.clamp(-1.0, 1.0)

    # Direction becomes physically noisy at very low wind speed; reduce its loss weight there.
    speed_weight = (true_norm / 5.0).clamp(max=1.0)
    return (angular * speed_weight).sum() / speed_weight.sum().clamp_min(1.0)


def train_one_epoch(
    model: nn.Module,
    arrays: dict[str, np.ndarray],
    optimizer: torch.optim.Optimizer,
    regression_loss_fn: nn.Module,
    event_loss_fn: nn.Module,
    device: torch.device,
    batch_size: int,
    event_loss_weight: float,
    direction_loss_weight: float,
    rng: np.random.Generator,
    shuffle_blocks: bool,
    residual_regression: bool,
    uv_feature_indices: tuple[int, int],
    target_uv_mean: torch.Tensor,
    target_uv_std: torch.Tensor,
) -> dict[str, float]:
    model.train()
    n = arrays["X"].shape[0]
    total_loss = 0.0
    total_reg = 0.0
    total_event = 0.0
    total_direction = 0.0
    total_count = 0

    for start, end in iter_slices(n, batch_size, rng, shuffle_blocks):
        xb = numpy_batch(arrays["X"], start, end).to(device)
        y_uv = numpy_batch(arrays["y_uv"], start, end).to(device)
        y_event = numpy_batch(arrays["y_event"], start, end).to(device)

        optimizer.zero_grad(set_to_none=True)
        pred_uv, event_logits = model(xb)
        y_reg = regression_target(y_uv, xb, residual_regression, uv_feature_indices)
        reg_loss = regression_loss_fn(pred_uv, y_reg)
        event_loss = event_loss_fn(event_logits, y_event)
        if direction_loss_weight > 0.0:
            direction_loss = wind_direction_loss(
                pred_uv,
                y_uv,
                xb,
                residual_regression,
                uv_feature_indices,
                target_uv_mean,
                target_uv_std,
            )
        else:
            direction_loss = pred_uv.new_tensor(0.0)
        loss = reg_loss + event_loss_weight * event_loss + direction_loss_weight * direction_loss
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        batch_count = end - start
        total_loss += float(loss.detach().cpu()) * batch_count
        total_reg += float(reg_loss.detach().cpu()) * batch_count
        total_event += float(event_loss.detach().cpu()) * batch_count
        total_direction += float(direction_loss.detach().cpu()) * batch_count
        total_count += batch_count

    return {
        "loss": total_loss / total_count,
        "regression_loss": total_reg / total_count,
        "event_loss": total_event / total_count,
        "direction_loss": total_direction / total_count,
    }


@torch.no_grad()
def evaluate_loss(
    model: nn.Module,
    arrays: dict[str, np.ndarray],
    regression_loss_fn: nn.Module,
    event_loss_fn: nn.Module,
    device: torch.device,
    batch_size: int,
    event_loss_weight: float,
    direction_loss_weight: float,
    residual_regression: bool,
    uv_feature_indices: tuple[int, int],
    target_uv_mean: torch.Tensor,
    target_uv_std: torch.Tensor,
) -> dict[str, float]:
    model.eval()
    n = arrays["X"].shape[0]
    total_loss = 0.0
    total_reg = 0.0
    total_event = 0.0
    total_direction = 0.0
    total_count = 0

    for start, end in iter_slices(n, batch_size, np.random.default_rng(0), shuffle_blocks=False):
        xb = numpy_batch(arrays["X"], start, end).to(device)
        y_uv = numpy_batch(arrays["y_uv"], start, end).to(device)
        y_event = numpy_batch(arrays["y_event"], start, end).to(device)
        pred_uv, event_logits = model(xb)
        y_reg = regression_target(y_uv, xb, residual_regression, uv_feature_indices)
        reg_loss = regression_loss_fn(pred_uv, y_reg)
        event_loss = event_loss_fn(event_logits, y_event)
        if direction_loss_weight > 0.0:
            direction_loss = wind_direction_loss(
                pred_uv,
                y_uv,
                xb,
                residual_regression,
                uv_feature_indices,
                target_uv_mean,
                target_uv_std,
            )
        else:
            direction_loss = pred_uv.new_tensor(0.0)
        loss = reg_loss + event_loss_weight * event_loss + direction_loss_weight * direction_loss
        batch_count = end - start
        total_loss += float(loss.detach().cpu()) * batch_count
        total_reg += float(reg_loss.detach().cpu()) * batch_count
        total_event += float(event_loss.detach().cpu()) * batch_count
        total_direction += float(direction_loss.detach().cpu()) * batch_count
        total_count += batch_count

    return {
        "loss": total_loss / total_count,
        "regression_loss": total_reg / total_count,
        "event_loss": total_event / total_count,
        "direction_loss": total_direction / total_count,
    }


@torch.no_grad()
def predict_split(
    model: nn.Module,
    arrays: dict[str, np.ndarray],
    device: torch.device,
    batch_size: int,
    residual_regression: bool,
    uv_feature_indices: tuple[int, int],
) -> tuple[np.ndarray, np.ndarray]:
    model.eval()
    n = arrays["X"].shape[0]
    future_steps = arrays["y_uv"].shape[1]
    event_count = arrays["y_event"].shape[1]
    pred_uv_scaled = np.empty((n, future_steps, 2), dtype=np.float32)
    pred_event_prob = np.empty((n, event_count), dtype=np.float32)

    for start, end in iter_slices(n, batch_size, np.random.default_rng(0), shuffle_blocks=False):
        xb = numpy_batch(arrays["X"], start, end).to(device)
        pred_uv, event_logits = model(xb)
        pred_uv = full_scaled_prediction(pred_uv, xb, residual_regression, uv_feature_indices)
        pred_uv_scaled[start:end] = pred_uv.detach().cpu().numpy().astype("float32")
        pred_event_prob[start:end] = torch.sigmoid(event_logits).detach().cpu().numpy().astype("float32")

    return pred_uv_scaled, pred_event_prob


def inverse_scale_uv(pred_uv_scaled: np.ndarray, scaler: dict) -> np.ndarray:
    target_scaler = scaler["target_uv_scaler"]
    mean = np.array(
        [target_scaler["wind_u_ms"]["mean"], target_scaler["wind_v_ms"]["mean"]],
        dtype=np.float32,
    )
    std = np.array(
        [target_scaler["wind_u_ms"]["std"], target_scaler["wind_v_ms"]["std"]],
        dtype=np.float32,
    )
    return pred_uv_scaled * std + mean


def speed_direction_from_uv(uv: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    u = uv[:, :, 0]
    v = uv[:, :, 1]
    speed = np.sqrt(u**2 + v**2)
    direction = (np.rad2deg(np.arctan2(-u, -v)) + 360.0) % 360.0
    return speed.astype("float32"), direction.astype("float32")


def circular_diff_deg(target: np.ndarray, base: np.ndarray) -> np.ndarray:
    return (target - base + 180.0) % 360.0 - 180.0


def regression_metrics(
    split: str,
    model_name: str,
    pred_uv_raw: np.ndarray,
    y_uv_raw: np.ndarray,
    y_speed_dir_raw: np.ndarray,
) -> list[dict[str, object]]:
    pred_speed, pred_dir = speed_direction_from_uv(pred_uv_raw)
    true_speed = y_speed_dir_raw[:, :, 0]
    true_dir = y_speed_dir_raw[:, :, 1]

    uv_error = pred_uv_raw - y_uv_raw
    speed_error = pred_speed - true_speed
    direction_error = circular_diff_deg(pred_dir, true_dir)

    rows: list[dict[str, object]] = []

    def build_row(scope: str, uv_err: np.ndarray, speed_err: np.ndarray, dir_err: np.ndarray) -> dict[str, object]:
        return {
            "model": model_name,
            "split": split,
            "scope": scope,
            "vector_mae_ms": float(np.mean(np.abs(uv_err))),
            "vector_rmse_ms": float(np.sqrt(np.mean(uv_err**2))),
            "speed_mae_ms": float(np.mean(np.abs(speed_err))),
            "speed_rmse_ms": float(np.sqrt(np.mean(speed_err**2))),
            "direction_mae_deg": float(np.mean(np.abs(dir_err))),
        }

    rows.append(build_row("all_future_steps", uv_error, speed_error, direction_error))
    for step in range(pred_uv_raw.shape[1]):
        rows.append(
            build_row(
                f"tplus_{(step + 1) * 10}m",
                uv_error[:, step, :],
                speed_error[:, step],
                direction_error[:, step],
            )
        )
    return rows


def binary_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float]:
    true = y_true.astype(bool)
    pred = y_pred.astype(bool)
    tp = int(np.logical_and(true, pred).sum())
    fp = int(np.logical_and(~true, pred).sum())
    fn = int(np.logical_and(true, ~pred).sum())
    tn = int(np.logical_and(~true, ~pred).sum())
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
    false_alarm_rate = fp / (fp + tn) if (fp + tn) else 0.0
    return {
        "prevalence": float(true.mean()),
        "predicted_rate": float(pred.mean()),
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "false_alarm_rate": false_alarm_rate,
    }


def best_f1_thresholds(y_true: np.ndarray, probs: np.ndarray) -> np.ndarray:
    thresholds = np.linspace(0.05, 0.95, 19, dtype=np.float32)
    selected = np.empty(probs.shape[1], dtype=np.float32)
    for col in range(probs.shape[1]):
        best_threshold = 0.5
        best_score = -1.0
        for threshold in thresholds:
            metrics = binary_metrics(y_true[:, col], probs[:, col] >= threshold)
            if metrics["f1"] > best_score:
                best_score = metrics["f1"]
                best_threshold = float(threshold)
        selected[col] = best_threshold
    return selected


def event_metrics(
    split: str,
    model_name: str,
    y_true: np.ndarray,
    probs: np.ndarray,
    thresholds: np.ndarray,
    event_names: list[str],
) -> list[dict[str, object]]:
    rows = []
    for idx, event_name in enumerate(event_names):
        pred = probs[:, idx] >= thresholds[idx]
        rows.append(
            {
                "model": model_name,
                "split": split,
                "event": event_name,
                "threshold": float(thresholds[idx]),
                **binary_metrics(y_true[:, idx], pred),
            }
        )
    return rows


def shape_checks(arrays: dict[str, dict[str, np.ndarray]], metadata: dict) -> None:
    expected_history = metadata["history_steps"]
    expected_future = metadata["future_steps"]
    expected_features = len(metadata["feature_columns"])
    expected_events = len(metadata["event_columns"])
    for split, split_arrays in arrays.items():
        x = split_arrays["X"]
        y_uv = split_arrays["y_uv"]
        y_event = split_arrays["y_event"]
        if x.ndim != 3 or x.shape[1:] != (expected_history, expected_features):
            raise SystemExit(f"Unexpected X shape for {split}: {x.shape}")
        if y_uv.ndim != 3 or y_uv.shape[1:] != (expected_future, 2):
            raise SystemExit(f"Unexpected y_uv shape for {split}: {y_uv.shape}")
        if y_event.ndim != 2 or y_event.shape[1] != expected_events:
            raise SystemExit(f"Unexpected y_event shape for {split}: {y_event.shape}")
        if x.shape[0] != y_uv.shape[0] or x.shape[0] != y_event.shape[0]:
            raise SystemExit(f"Sample count mismatch for {split}")
        if not np.isfinite(np.asarray(x[: min(1024, len(x))])).all():
            raise SystemExit(f"Non-finite X values found in {split} preview.")


def uv_feature_indices(metadata: dict) -> tuple[int, int]:
    feature_columns = metadata["feature_columns"]
    try:
        return feature_columns.index("wind_u_ms"), feature_columns.index("wind_v_ms")
    except ValueError as exc:
        raise SystemExit("Residual regression requires wind_u_ms and wind_v_ms input features.") from exc


def target_uv_tensors(scaler: dict, device: torch.device) -> tuple[torch.Tensor, torch.Tensor]:
    target_scaler = scaler["target_uv_scaler"]
    mean = torch.tensor(
        [target_scaler["wind_u_ms"]["mean"], target_scaler["wind_v_ms"]["mean"]],
        dtype=torch.float32,
        device=device,
    ).view(1, 1, 2)
    std = torch.tensor(
        [target_scaler["wind_u_ms"]["std"], target_scaler["wind_v_ms"]["std"]],
        dtype=torch.float32,
        device=device,
    ).view(1, 1, 2)
    return mean, std


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    device = choose_device(args.device)
    torch.set_num_threads(args.threads)
    set_seed(args.seed)

    arrays, metadata, scaler = load_dataset(args.dataset_dir)
    shape_checks(arrays, metadata)

    input_size = arrays["train"]["X"].shape[2]
    future_steps = arrays["train"]["y_uv"].shape[1]
    event_count = arrays["train"]["y_event"].shape[1]
    uv_indices = uv_feature_indices(metadata)
    target_uv_mean, target_uv_std = target_uv_tensors(scaler, device)
    model = WindRNN(
        input_size=input_size,
        hidden_size=args.hidden_size,
        future_steps=future_steps,
        event_count=event_count,
        num_layers=args.num_layers,
        dropout=args.dropout,
        model_type=args.model_type,
    ).to(device)

    pos_weight = torch.tensor(event_pos_weight(arrays["train"]["y_event"]), dtype=torch.float32, device=device)
    regression_loss_fn = nn.MSELoss()
    event_loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=args.lr_factor,
        patience=args.lr_patience,
    )

    config = TrainConfig(
        dataset_dir=str(args.dataset_dir),
        output_dir=str(args.output_dir),
        epochs=args.epochs,
        batch_size=args.batch_size,
        hidden_size=args.hidden_size,
        num_layers=args.num_layers,
        dropout=args.dropout,
        learning_rate=args.learning_rate,
        weight_decay=args.weight_decay,
        event_loss_weight=args.event_loss_weight,
        direction_loss_weight=args.direction_loss_weight,
        patience=args.patience,
        lr_patience=args.lr_patience,
        lr_factor=args.lr_factor,
        seed=args.seed,
        threads=args.threads,
        shuffle_blocks=not args.no_shuffle_blocks,
        threshold_mode=args.threshold_mode,
        residual_regression=args.residual_regression,
        model_type=args.model_type,
        device=str(device),
    )
    (args.output_dir / "lstm_config.json").write_text(
        json.dumps(
            {
                **asdict(config),
                "input_size": input_size,
                "future_steps": future_steps,
                "event_count": event_count,
                "event_pos_weight": [float(x) for x in pos_weight.detach().cpu().numpy()],
                "metadata_source": str(args.dataset_dir / "metadata.json"),
                "torch_version": torch.__version__,
                "uv_feature_indices": list(uv_indices),
                "parameter_count": sum(p.numel() for p in model.parameters() if p.requires_grad),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(f"Device: {device}")
    print(f"Train samples: {arrays['train']['X'].shape[0]}")
    print(f"Validation samples: {arrays['validation']['X'].shape[0]}")
    print(f"Test samples: {arrays['test']['X'].shape[0]}")
    print(f"Input shape: history={metadata['history_steps']} features={input_size}")
    print(f"Output shape: future={future_steps} uv=2 events={event_count}")
    print(f"Model: {args.model_type} layers={args.num_layers} hidden={args.hidden_size}")
    print(f"Trainable parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad)}")

    history_rows = []
    best_val_loss = math.inf
    best_epoch = -1
    stale_epochs = 0
    rng = np.random.default_rng(args.seed)

    for epoch in range(1, args.epochs + 1):
        train_metrics = train_one_epoch(
            model,
            arrays["train"],
            optimizer,
            regression_loss_fn,
            event_loss_fn,
            device,
            args.batch_size,
            args.event_loss_weight,
            args.direction_loss_weight,
            rng,
            shuffle_blocks=not args.no_shuffle_blocks,
            residual_regression=args.residual_regression,
            uv_feature_indices=uv_indices,
            target_uv_mean=target_uv_mean,
            target_uv_std=target_uv_std,
        )
        val_metrics = evaluate_loss(
            model,
            arrays["validation"],
            regression_loss_fn,
            event_loss_fn,
            device,
            args.batch_size,
            args.event_loss_weight,
            args.direction_loss_weight,
            residual_regression=args.residual_regression,
            uv_feature_indices=uv_indices,
            target_uv_mean=target_uv_mean,
            target_uv_std=target_uv_std,
        )
        current_lr = float(optimizer.param_groups[0]["lr"])
        row = {
            "epoch": epoch,
            "learning_rate": current_lr,
            **{f"train_{k}": v for k, v in train_metrics.items()},
            **{f"validation_{k}": v for k, v in val_metrics.items()},
        }
        history_rows.append(row)
        pd.DataFrame(history_rows).to_csv(args.output_dir / "lstm_training_history.csv", index=False)
        print(
            "epoch={epoch} lr={lr:.6g} train_loss={train_loss:.6f} val_loss={val_loss:.6f} "
            "train_reg={train_reg:.6f} val_reg={val_reg:.6f} "
            "train_event={train_event:.6f} val_event={val_event:.6f} "
            "train_dir={train_dir:.6f} val_dir={val_dir:.6f}".format(
                epoch=epoch,
                lr=current_lr,
                train_loss=train_metrics["loss"],
                val_loss=val_metrics["loss"],
                train_reg=train_metrics["regression_loss"],
                val_reg=val_metrics["regression_loss"],
                train_event=train_metrics["event_loss"],
                val_event=val_metrics["event_loss"],
                train_dir=train_metrics["direction_loss"],
                val_dir=val_metrics["direction_loss"],
            ),
            flush=True,
        )

        if val_metrics["loss"] < best_val_loss:
            best_val_loss = val_metrics["loss"]
            best_epoch = epoch
            stale_epochs = 0
            torch.save(
                {
                    "model_state_dict": model.state_dict(),
                    "config": asdict(config),
                    "metadata": metadata,
                    "best_epoch": best_epoch,
                    "best_validation_loss": best_val_loss,
                },
                args.output_dir / "lstm_best.pt",
            )
        else:
            stale_epochs += 1
            if stale_epochs >= args.patience:
                print(f"Early stopping after epoch {epoch}; best epoch was {best_epoch}.", flush=True)
                break
        scheduler.step(val_metrics["loss"])

    checkpoint = torch.load(args.output_dir / "lstm_best.pt", map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])

    val_pred_uv_scaled, val_event_prob = predict_split(
        model,
        arrays["validation"],
        device,
        args.batch_size,
        residual_regression=args.residual_regression,
        uv_feature_indices=uv_indices,
    )
    test_pred_uv_scaled, test_event_prob = predict_split(
        model,
        arrays["test"],
        device,
        args.batch_size,
        residual_regression=args.residual_regression,
        uv_feature_indices=uv_indices,
    )
    val_pred_uv_raw = inverse_scale_uv(val_pred_uv_scaled, scaler)
    test_pred_uv_raw = inverse_scale_uv(test_pred_uv_scaled, scaler)

    reg_rows = []
    model_name = f"{args.model_type}_dual_head"
    if args.residual_regression:
        model_name = f"residual_{model_name}"
    if args.direction_loss_weight > 0:
        model_name = f"{model_name}_direction_loss"
    reg_rows.extend(
        regression_metrics(
            "validation",
            model_name,
            val_pred_uv_raw,
            np.asarray(arrays["validation"]["y_uv_raw"]),
            np.asarray(arrays["validation"]["y_speed_dir_raw"]),
        )
    )
    reg_rows.extend(
        regression_metrics(
            "test",
            model_name,
            test_pred_uv_raw,
            np.asarray(arrays["test"]["y_uv_raw"]),
            np.asarray(arrays["test"]["y_speed_dir_raw"]),
        )
    )
    reg_metrics = pd.DataFrame(reg_rows)
    reg_metrics.to_csv(args.output_dir / "lstm_regression_metrics.csv", index=False)

    event_names = metadata["event_columns"]
    if args.threshold_mode == "best_f1":
        thresholds = best_f1_thresholds(np.asarray(arrays["validation"]["y_event"]), val_event_prob)
    else:
        thresholds = np.full(event_count, 0.5, dtype=np.float32)
    event_rows = []
    event_rows.extend(
        event_metrics(
            "validation",
            model_name,
            np.asarray(arrays["validation"]["y_event"]),
            val_event_prob,
            thresholds,
            event_names,
        )
    )
    event_rows.extend(
        event_metrics(
            "test",
            model_name,
            np.asarray(arrays["test"]["y_event"]),
            test_event_prob,
            thresholds,
            event_names,
        )
    )
    event_metrics_frame = pd.DataFrame(event_rows)
    event_metrics_frame.to_csv(args.output_dir / "lstm_event_metrics.csv", index=False)
    (args.output_dir / "lstm_event_thresholds.json").write_text(
        json.dumps(
            {
                "threshold_mode": args.threshold_mode,
                "thresholds": {name: float(thresholds[idx]) for idx, name in enumerate(event_names)},
                "selected_on": "validation",
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    summary = {
        "best_epoch": best_epoch,
        "best_validation_loss": best_val_loss,
        "regression_metrics_csv": str(args.output_dir / "lstm_regression_metrics.csv"),
        "event_metrics_csv": str(args.output_dir / "lstm_event_metrics.csv"),
        "checkpoint": str(args.output_dir / "lstm_best.pt"),
    }
    (args.output_dir / "lstm_run_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print("\nRegression metrics")
    print(reg_metrics.to_string(index=False))
    print("\nEvent metrics")
    print(event_metrics_frame.to_string(index=False))
    print(f"\nBest epoch: {best_epoch}; best validation loss: {best_val_loss:.6f}")


if __name__ == "__main__":
    main()
